# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e91bc1c6da4d192bc411bd8cc3035885894e63503695030e167f46acab99c0e442b31efbb5f7a88342d6f216865d29e97b7519479df23e5df3d276fed8c19201

test:
  secret_key_base: 48605db7565c88002cdc4750ba17dd68ce3ff6c2e3a63633274a175931a22299af2f0258ed08f9f4397cb383cb7a6b4925d59be94b36b348f6259c2586d2cac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
